#!/bin/sh
#################################################################
# chkconfig: 12345 99 98
# description: OpenSource Simple Shutdown Service
# processname: ssdService
#----------------------------------------------------------------
if [ -f /etc/rc.d/init.d/functions ]; then
	. /etc/rc.d/init.d/functions
fi

BINPATH=/usr/lib/ssd/master
PROGNAME=ssdService
start()
{
	ps -C $PROGNAME >/dev/null
	i=`echo $?`
	if [ $i -ne 0 ]; then
		echo -n $"Starting $PROGNAME:"
		echo
		if [ -x $BINPATH/$PROGNAME -a -x $BINPATH/AgentManager ];
		then
			$BINPATH/$PROGNAME
		fi
	fi
}

stop()
{
	echo -n $"Stoping $PROGNAME:"
	echo
	if [ -x $BINPATH/$PROGNAME -a -x $BINPATH/AgentManager ];	
	then   
		$BINPATH/AgentManager stop
		sleep 3
	fi
}

restart()
{
	ps -C $PROGNAME >/dev/null
	i=`echo $?`
	if [ $i -ne 0 ]; then
			echo "Warning: Simple Shutdown is not running"
		else
			stop
			sleep 4
			start
	fi
}

my_status()
{
  if [ -f /etc/rc.d/init.d/functions ]; then
          status $PROGNAME
		else
			ps -C $PROGNAME >/dev/null
			i=`echo $?`
			if [ $i -ne 0 ]; then
	      echo "Simple Shutdown is not running"
				echo
					else
						echo "Simple Shutdown is running"
						echo
	    fi
   fi
}
case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload|restart)
		restart
        	;;
	status)
		my_status
        	;;
	*)
esac
